// src/components/TwitchDigits/index.vue
<template>
<div class="twitch-digits">
    <header class="header">
        <div class="header-inner">
            <h1 class="headline"><a class="logo" href="/">twitch digits</a></h1>
            <h2 class="chart-label">viewership as of {{ prettyTime }}</h2>
        </div>
        <fork-me href="https://github.com/pBun/twitch-digits"></fork-me>
    </header>
    <main class="main">
        <snapshot-chart class="snapshot-chart" :snapshot="snapshot" :class="{ 'visible': (initialized && !loading) }"></snapshot-chart>
        <control-panel class="control-panel" toggle-text="timeline" :open="controlsOpen" @open="handleControlsState" :class="{ 'visible': initialized }">
            <day-menu :days="days" :selected="filteredDay" @linkClick="filterDay"></day-menu>
            <snapshot-menu :times="filteredTimes" :selected="selectedTime" @linkClick="refresh"></snapshot-menu>
        </control-panel>
    </main>
    <walking-loader class="loader" :class="{ 'visible': (!initialized || loading) }"></walking-loader>
    <error-modal :error="error" :class="{ 'visible': error }"></error-modal>
</div>
</template>

<script>
import util from '../../helpers/util';
import api from '../../helpers/twitchPub';
import moment from 'moment';
import WalkingLoader from '../WalkingLoader.vue';
import ErrorModal from '../ErrorModal.vue';
import ControlPanel from '../ControlPanel.vue';
import ForkMe from '../ForkMe.vue';
import SnapshotMenu from './SnapshotMenu.vue';
import DayMenu from './DayMenu.vue';
import SnapshotChart from './SnapshotChart.vue';
export default {
    data() {
        return {
            initialized: false,
            loading: false,
            loadingTimeout: null,
            loadingDelay: 250,
            error: null,
            times: [],
            selectedTime: null,
            selectedDay: null,
            now: null,
            snapshot: null,
            controlsOpen: false
        }
    },
    computed: {
        prettyTime(scope) {
            var t = scope.selectedTime;
            if (!t) return 'now';
            var diff = moment().diff(moment(t));
            var dur = moment.duration(diff);
            var d = Math.floor(dur.asDays());
            var h = Math.round(dur.asHours() - d * 24);
            return (d ? d + 'd ' : '') + (h ? h + 'h' : 'a few minutes') + ' ago';
        },
        days(scope) {
            if (!scope.times || !scope.times.length) return [];
            var days = scope.times.map(t => util.stripTime(t && t._time));
            var unique = {};
            days = days.filter(d => unique.hasOwnProperty(d) ? false : (unique[d] = true));
            var numDays = Math.min(days.length, 7);
            return days.slice(days.length - numDays, days.length);
        },
        filteredDay(scope) {
            if (scope.selectedDay) return scope.selectedDay;
            if (!scope.days || !scope.days.length) return util.stripTime(new Date());
            var latest = scope.days.reduce((a, b) => Math.max(a, b));
            return new Date(latest);
        },
        filteredTimes(scope) {
            return scope.times.filter(t => {
                return util.stripTime(t._time).getDate() === scope.filteredDay.getDate();
            });
        }
    },
    methods: {
        startLoading() {
            var scope = this;
            this.loadingTimeout = setTimeout(() => scope.loading = true, scope.loadingDelay);
        },
        stopLoading() {
            clearTimeout(this.loadingTimeout);
            this.loading = false
        },
        refresh(time) {
            this.controlsOpen = false;
            return this.loadSnapshot(time)
                .then(() => this.loadTimes());
        },
        setNow(s) {
            this.now = {
                'viewers': s.viewers,
                'channels': s.channels
            };
        },
        loadTimes() {
            this.startLoading();
            this.error = null;
            return api.get('snapshot/times')
                .then(t => {
                    t.push(this.now);
                    this.times = t;
                })
                .catch(err => this.error = err)
                .then(() => this.stopLoading());
        },
        loadSnapshot(time) {
            this.startLoading();
            this.error = null;
            this.selectedTime = time;
            var endpoint = time ? 'snapshot/' + time : 'snapshot';
            return api.get(endpoint)
                .then(s => {
                    if (!time) this.setNow(s);
                    this.snapshot = s
                })
                .catch(err => this.error = err)
                .then(() => this.stopLoading());
        },
        filterDay(day) {
            this.selectedDay = day;
        },
        handleControlsState(state) {
            this.controlsOpen = state;
        }
    },
    created() {
        this.refresh().then(() => this.initialized = true);
    },
    components: { SnapshotChart, WalkingLoader, ControlPanel, ErrorModal, SnapshotMenu, DayMenu, ForkMe }
}
</script>

<style>
.twitch-digits {
    height: 100%;
}
.twitch-digits .main {
    height: calc(85% - 2em - 20px);
    margin: 0 20px;
    position: relative;
}

/* header */
.twitch-digits .header {
    position: relative;
    text-align: center;
    height: 15%;
}
.twitch-digits .header .header-inner {
  position: absolute;
  top: 50%;
  left: 0;
  right: 0;
  transform: translateY(-50%);
}
.twitch-digits .header .logo {
    display: inline-block;
    font-size: 3.5em;
    font-weight: 100;
    line-height: 1em;
    letter-spacing: -0.05em;
    border-bottom: none;
    margin-bottom: 0.075em;
}
.twitch-digits .header .chart-label {
    letter-spacing: 0.025em;
}
.twitch-digits .fork-me {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    max-width: 25%;
}

/* loader */
.twitch-digits .loader {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  display: none;
}
.twitch-digits .loader.visible {
    display: block;
}

/* error */
.twitch-digits .error-modal {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 100%;
  display: none;
}
.twitch-digits .error-modal.visible {
    display: block;
}

/* control panel */
.twitch-digits .control-panel {
    opacity: 0;
    transition: 0.3s opacity;
}
.twitch-digits .control-panel.visible {
    opacity: 1;
}
.twitch-digits .control-content {
    font-size: 0.7em;
}
.twitch-digits .snapshot-menu {
    position: absolute;
    top: 2.3em;
    bottom: 0;
    left: 0;
    right: 0;
}

/* chart */
.twitch-digits .snapshot-chart {
    opacity: 0;
    transition: 0.3s opacity;
}
.twitch-digits .snapshot-chart.visible {
    opacity: 1;
}

/* responsive */
@media (max-width: 480px) {
    .twitch-digits .header .logo {
        font-size: 2.5em;
    }
}

</style>

// src/components/TwitchDigits/index.jsx
import React, { Component } from 'react';
import classNames from 'classnames';
import util from '../../helpers/util';
import api from '../../helpers/twitchPub';
import ForkMe from '../ForkMe/index.jsx';
import ErrorModal from '../ErrorModal/index.jsx';
import ControlPanel from '../ControlPanel/index.jsx';
import WalkingLoader from '../WalkingLoader/index.jsx';
import DayMenu from './DayMenu/index.jsx';
import './styles.css';

class TwitchDigits extends Component {
    
    constructor(props) {
        super(props);
        this.state = { 
            initialized: false,
            loading: false,
            loadingTimeout: null,
            loadingDelay: 250,
            error: null,
            times: [],
            selectedTime: null,
            selectedDay: null,
            now: null,
            snapshot: null,
            controlsOpen: false
        };
    };

    handleControlsToggle() {
        this.setState({controlsOpen: !this.state.controlsOpen})
    };
  
    render() {
        return ( 
            <div className={classNames('twitch-digits', {'initialized': this.state.initialized, 'loading': this.state.loading})}>
                <header className="header">
                    <div className="header-inner">
                        <h1 className="headline"><a className="logo" href="/">twitch digits</a></h1>
                        <h2 className="chart-label">viewership as of { util.prettyRelTime(this.state.selectedTime) }</h2>
                    </div>
                    <ForkMe href="https://github.com/pBun/twitch-digits" />
                </header>
                <main className="main">
                    <ControlPanel toggleText="timeline" open={this.state.controlsOpen} handleToggle={this.handleControlsToggle.bind(this)}>
                        {/*<DayMenu :days="days" :selected="filteredDay" @linkClick="filterDay" />*/}
                        {/*<SnapshotMenu :times="filteredTimes" :selected="selectedTime" @linkClick="refresh" />*/}
                    </ControlPanel>
                </main>
                <WalkingLoader />
                <ErrorModal error={this.state.error} />
            </div>
        );
    }
}

export default TwitchDigits;

//////////////////// END ////////////////////////////////////////

// <template>
// <div class="twitch-digits">
//     <main class="main">
//         <snapshot-chart class="snapshot-chart" :snapshot="snapshot" :class="{ 'visible': (initialized && !loading) }"></snapshot-chart>
//         <control-panel class="control-panel" toggle-text="timeline" :open="controlsOpen" @open="handleControlsState" :class="{ 'visible': initialized }">
//             <day-menu :days="days" :selected="filteredDay" @linkClick="filterDay"></day-menu>
//             <snapshot-menu :times="filteredTimes" :selected="selectedTime" @linkClick="refresh"></snapshot-menu>
//         </control-panel>
//     </main>
// </div>
// </template>

// <script>
// import WalkingLoader from '../WalkingLoader.vue';
// import ErrorModal from '../ErrorModal.vue';
// import ControlPanel from '../ControlPanel.vue';
// import ForkMe from '../ForkMe.vue';
// import SnapshotMenu from './SnapshotMenu.vue';
// import DayMenu from './DayMenu.vue';
// import SnapshotChart from './SnapshotChart.vue';
// export default {
//     data() {
//         return {
//             initialized: false,
//             loading: false,
//             loadingTimeout: null,
//             loadingDelay: 250,
//             error: null,
//             times: [],
//             selectedTime: null,
//             selectedDay: null,
//             now: null,
//             snapshot: null,
//             controlsOpen: false
//         }
//     },
//     computed: {
//         prettyTime(scope) {
//             var t = scope.selectedTime;
//             if (!t) return 'now';
//             var diff = moment().diff(moment(t));
//             var dur = moment.duration(diff);
//             var d = Math.floor(dur.asDays());
//             var h = Math.round(dur.asHours() - d * 24);
//             return (d ? d + 'd ' : '') + (h ? h + 'h' : 'a few minutes') + ' ago';
//         },
//         days(scope) {
//             if (!scope.times || !scope.times.length) return [];
//             var days = scope.times.map(t => util.stripTime(t && t._time));
//             var unique = {};
//             days = days.filter(d => unique.hasOwnProperty(d) ? false : (unique[d] = true));
//             var numDays = Math.min(days.length, 7);
//             return days.slice(days.length - numDays, days.length);
//         },
//         filteredDay(scope) {
//             if (scope.selectedDay) return scope.selectedDay;
//             if (!scope.days || !scope.days.length) return util.stripTime(new Date());
//             var latest = scope.days.reduce((a, b) => Math.max(a, b));
//             return new Date(latest);
//         },
//         filteredTimes(scope) {
//             return scope.times.filter(t => {
//                 return util.stripTime(t._time).getDate() === scope.filteredDay.getDate();
//             });
//         }
//     },
//     methods: {
//         startLoading() {
//             var scope = this;
//             this.loadingTimeout = setTimeout(() => scope.loading = true, scope.loadingDelay);
//         },
//         stopLoading() {
//             clearTimeout(this.loadingTimeout);
//             this.loading = false
//         },
//         refresh(time) {
//             this.controlsOpen = false;
//             return this.loadSnapshot(time)
//                 .then(() => this.loadTimes());
//         },
//         setNow(s) {
//             this.now = {
//                 'viewers': s.viewers,
//                 'channels': s.channels
//             };
//         },
//         loadTimes() {
//             this.startLoading();
//             this.error = null;
//             return api.get('snapshot/times')
//                 .then(t => {
//                     t.push(this.now);
//                     this.times = t;
//                 })
//                 .catch(err => this.error = err)
//                 .then(() => this.stopLoading());
//         },
//         loadSnapshot(time) {
//             this.startLoading();
//             this.error = null;
//             this.selectedTime = time;
//             var endpoint = time ? 'snapshot/' + time : 'snapshot';
//             return api.get(endpoint)
//                 .then(s => {
//                     if (!time) this.setNow(s);
//                     this.snapshot = s
//                 })
//                 .catch(err => this.error = err)
//                 .then(() => this.stopLoading());
//         },
//         filterDay(day) {
//             this.selectedDay = day;
//         },
//         handleControlsState(state) {
//             this.controlsOpen = state;
//         }
//     },
//     created() {
//         this.refresh().then(() => this.initialized = true);
//     },
//     components: { SnapshotChart, WalkingLoader, ControlPanel, ErrorModal, SnapshotMenu, DayMenu, ForkMe }
// }
// </script>
